import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ClientProvider from "~/components/client-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  // title: "Cardano2vn",
  // description: "Generated by create next app",
  
  // seo basic -- start
  title: {
    default: "Cardano2VN - Blockchain Innovation Hub",
    template: "%s | Cardano2VN"
  },
  description: "Cardano2VN is a leading blockchain innovation hub in Vietnam, specializing in Cardano ecosystem development, smart contracts, and decentralized applications.",
  keywords: ["Cardano", "blockchain", "Vietnam", "smart contracts", "DeFi", "cryptocurrency", "ADA", "web3"],
  authors: [{ name: "Cardano2VN Team" }],
  creator: "Cardano2VN",
  publisher: "Cardano2VN",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL("https://cardano2vn.io"),
  alternates: {
    canonical: "/",
  },
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon-16x16.png",
    apple: "/apple-touch-icon.png",
  },
  manifest: "/site.webmanifest",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://cardano2vn.io",
    title: "Cardano2VN - Blockchain Innovation Hub",
    description: "Cardano2VN is a leading blockchain innovation hub in Vietnam, specializing in Cardano ecosystem development, smart contracts, and decentralized applications.",
    siteName: "Cardano2VN",
    images: [
      {
        url: "/images/og-image.png",
        width: 1200,
        height: 630,
        alt: "Cardano2VN - Blockchain Innovation Hub",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Cardano2VN - Blockchain Innovation Hub",
    description: "Cardano2VN is a leading blockchain innovation hub in Vietnam, specializing in Cardano ecosystem development, smart contracts, and decentralized applications.",
    images: ["/images/og-image.png"],
    creator: "@cardano2vn",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  verification: {
    google: "####",
  },
  other: {
    "theme-color": "#ffffff",
    "msapplication-TileColor": "#da532c",
  },
  // seo basic -- end
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} suppressHydrationWarning>
        <ClientProvider>
          {children}
        </ClientProvider>
      </body>
    </html>
  );
}
