spring.application.name=server

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/lmsdb
spring.datasource.username=admin
spring.datasource.password=c2vn
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate (ORM)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.hikari.maximum-pool-size=10

# Redis
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.password=

# JWT
jwt.signer-key=VsRAwYduBgEG4y7xykcV6dDFxoefDJpSnXLjnf/yyR9BJsCmQvSout7/qpithRnD
jwt.valid-duration=3600
jwt.refreshable-duration=36000

#Spring security
spring.security.user.name=admin
spring.security.user.password=c2vn